CREATE TABLE "users" (
    "id" INT UNIQUE NOT NULL PRIMARY KEY,
    "username" TEXT UNIQUE NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
